### ISSUE TITLE
Key Path

### ISSUE THREAD

**Issue by MoonKidd** [twitter-picbot/twitter-picbot#8]
Key Path isn't working? Although I'm not 100% sure how to set it up, it states something is missing. I tried npm keypath install, but wasn't sure what to do next.

**Comment by RecuencoJones** [comment]
Hi @MoonKidd,

Could you please share:
- how are you running the app 
- the error log

It will help me understanding your issue.
Thanks!

**Comment by MoonKidd** [comment]
I am running the app using the node command prompt. I really think I'm getting the key path wrong since it's new to me. I use npm install keypath in the folder with the keys but I don't think that's right. I don't understand the [--keys=keys-path] part of the instructions fully, either. I'm really sorry for being this stupid with code, lol.

**Comment by RecuencoJones** [comment]
I don't think you need to use `keypath` module, you need to indicate the relative or absolute path to the directory containing the keys in a format like [this](https://github.com/twitter-picbot/twitter-picbot/blob/develop/keys.json), where you will need to replace the values with some valid Twitter credentials.

I'd recommend, instead of adding the --keys param, to use the default configuration.

By default the bot uses the `keys.json` file found at the root of the project, you can replace the values with your credentials there.

**Comment by MoonKidd** [comment]
Okay. so I did npm start -- [--query=botw] [--interval=minutes: 10] and it's giving me the same error as before: Error: Cannot find module 'es6-polyfills/lib/polyfills/object'

**Comment by RecuencoJones** [comment]
`[--arg-name=arg-value]` in the documentation means that the argument is optional.

Also, `interval` must be a CRON expression, every 10 minutes would be like this: `0 */10 * * * *` which means `On the second 0, every 10 minutes, every hour, every day, every month, every day of the week`.
Check [node-cron](https://github.com/merencia/node-cron) documentation.

So, you must run the app like this:

```
npm start -- --query=botw --interval='0 */10 * * * *'
```

Regarding the other error:
- Which versions of node and npm are you using? You can check them by running `node -v` and `npm -v`
- Did you run `npm install` before running the app?

**Comment by MoonKidd** [comment]
I ran npm install and tried the new command. I am using version 8.4.0

**Comment by RecuencoJones** [comment]
Did it work? Else, I might need further error details,  like the output in the console.

**Comment by MoonKidd** [comment]
> twitter-picbot@1.1.1 start C:\Users\hidas\Downloads\twitter-picbot-develop\twitter-picbot-develop
> node app/index.js "--query=botw" "--interval='0" "*/10" "*" "*" "*" "*'"

module.js:491
    throw err;
    ^

Error: Cannot find module 'es6-polyfills/lib/polyfills/object'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at C:\Users\hidas\Downloads\twitter-picbot-develop\twitter-picbot-develop\node_modules\loglevel-message-prefix\lib\main.js:40:34
    at Object.<anonymous> (C:\Users\hidas\Downloads\twitter-picbot-develop\twitter-picbot-develop\node_modules\loglevel-message-prefix\lib\main.js:45:2)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! twitter-picbot@1.1.1 start: `node app/index.js "--query=botw" "--interval='0" "*/10" "*" "*" "*" "*'"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the twitter-picbot@1.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hidas\AppData\Roaming\npm-cache\_logs\2017-10-05T05_48_38_866Z-debug.log

**Comment by RecuencoJones** [comment]
@MoonKidd Looks like the package `loglevel-message-prefix` was outdated in favor of another package and it caused problems with missing polyfills, I just merged a fix for it. Please, get the latest version from develop branch, reinstall dependencies and let me know if you get any more issues.

**Comment by MoonKidd** [comment]
Thanks, that problem was fixed, but now it's reading that `npm start -- --query=botw --interval='0 */10 * * * *'` is a invalid expression for second

**Comment by RecuencoJones** [comment]
Just tried running on my windows laptop `npm start -- --query=botw --interval='0 */10 * * * *'`, it started running the process every 10 minutes.

**Comment by MoonKidd** [comment]
https://imgur.com/a/xMKGE weird

**Comment by RecuencoJones** [comment]
Can you try replacing `'` by `"`?

`npm start -- --query=botw --interval="0 */10 * * * *"`

**Comment by MoonKidd** [comment]
Now it says 

```
[2017-10-5 12:26:00 INFO]: Starting process.
(node:17084) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'statusCode' of undefined
(node:17084) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2017-10-5 12:27:00 INFO]: Starting process.
(node:17084) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): TypeError: Cannot read property 'statusCode' of undefined
```

**Comment by RecuencoJones** [comment]
Did you set some valid twitter credentials in root `keys.json` and DeviantArt credentials in the plugin `keys.json`?

**Comment by MoonKidd** [comment]
Yes, I did.

**Comment by RecuencoJones** [comment]
There must be something wrong with the credentials, did you try them before to check whether you could perform requests to Twitter and DeviantArt APIs?

**Comment by MoonKidd** [comment]
Nope, not sure how, but it's the exact credentials I got from both sites.

**Comment by RecuencoJones** [comment]
Understood, I will try to prepare some more advanced and in-depth guide on how to get and test the credentials ☺️

**Comment by MoonKidd** [comment]
Okay, I'm trying to re-download and re-do everything as well to make sure
